bbortt/event-planner

src/test/java/io/github/bbortt/event/planner/repository/CustomAuditEventRepositoryIT.java, src/test/java/io/github/bbortt/event/planner/security/DomainUserDetailsServiceIT.java, src/test/java/io/github/bbortt/event/planner/service/AuditEventServiceIT.java, src/test/java/io/github/bbortt/event/planner/service/MailServiceIT.java, src/test/java/io/github/bbortt/event/planner/service/UserServiceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/AccountResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/AuditResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/EventResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/InvitationResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/LocationResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/ProjectResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/ResponsibilityResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/RoleResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/SectionResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/UserJWTControllerIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/UserResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/errors/ExceptionTranslatorIT.java
=> #36 integration tests use global configuration.

.travis.yml, README.md
=> #42 create codecov report after_success.

src/main/webapp/app/shared/auth/has-any-role.directive.ts
PR contains:
* enhanced documentation for `*hasAnyRole` directive
=> #55 update has-any-role directive instructions.

src/main/webapp/app/view/create-project/create-project-modal.component.scss, src/main/webapp/content/scss/global.scss
we will have multiple modals in the future.
=> move modal-content styles to global scss.

src/main/java/io/github/bbortt/event/planner/service/ProjectService.java, src/main/java/io/github/bbortt/event/planner/web/rest/ProjectResource.java, src/main/java/io/github/bbortt/event/planner/web/rest/ResponsibilityResource.java, src/main/webapp/app/entities/responsibility/responsibility.service.ts, src/test/java/io/github/bbortt/event/planner/web/rest/ProjectResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/ResponsibilityResourceIT.java
The responsibilities were not loaded at all. A previous commit must have broken this functionality.
=> fix(responsibilities): load responsibilites per project

src/main/webapp/app/view/create-project/project-create.component.ts
Since we save the role per project on the account we need to refetch the account details after creating a project.
closes #64
=> fix(project-create): refetch the identity after creating a project

src/main/java/io/github/bbortt/event/planner/domain/Location.java, src/main/resources/db/migration/V2020.11.20.13.15__location_remove_dates.sql, src/main/webapp/app/entities/location/location.service.ts, src/main/webapp/app/shared/model/location.model.ts, src/main/webapp/i18n/de/location.json, src/main/webapp/i18n/en/location.json, src/test/java/io/github/bbortt/event/planner/web/rest/LocationResourceIT.java, src/test/javascript/spec/app/entities/location/location.service.spec.ts
basically:
```bash
diff --git a/src/main/java/io/github/bbortt/event/planner/domain/Location.java b/src/main/java/io/github/bbortt/event/planner/domain/Location.java
index c341ddb..8733f2c 100644
--- a/src/main/java/io/github/bbortt/event/planner/domain/Location.java
+++ b/src/main/java/io/github/bbortt/event/planner/domain/Location.java
@@ -45,14 +45,6 @@ public class Location implements Serializable {
@Column(name = "name", length = 50, nullable = false)
private String name;
-    @NotNull
-    @Column(name = "date_from", nullable = false)
-    private ZonedDateTime dateFrom;
-
-    @NotNull
-    @Column(name = "date_to", nullable = false)
-    private ZonedDateTime dateTo;
-
@ManyToOne(optional = false)
@NotNull
@JsonIgnoreProperties(value = "locations", allowSetters = true)
```
=> #54 remove Location dateFrom and dateTo. this is covered by TimeSlots.

src/main/java/io/github/bbortt/event/planner/config/SecurityConfiguration.java, src/main/resources/config/application.yml
frontend must query active profiles.
=> reenable info endpoint. 

src/main/webapp/app/core/auth/account.service.ts, src/main/webapp/app/view/my-projects/my-projects.component.html, src/main/webapp/app/view/my-projects/my-projects.component.scss, src/main/webapp/app/view/project/admin/navbar/project-navbar.component.html
=> #81 fix project card responsive display.

src/main/webapp/app/core/user/user.service.ts
@zeroplexer try this. please run `npm install` too.
solves #95.
=> #95 fix user resource urls.

src/main/java/io/github/bbortt/event/planner/service/ProjectService.java, src/test/java/io/github/bbortt/event/planner/service/ProjectServiceUnitTest.java
frontend does already check `startTime` < `endTime`. backend did not 🚀 
closes #39.
=> #39 backend project time validation.

package-lock.json, package.json, src/main/java/io/github/bbortt/event/planner/repository/InvitationRepository.java, src/main/java/io/github/bbortt/event/planner/repository/LocationTimeSlotRepository.java, src/main/java/io/github/bbortt/event/planner/repository/SectionRepository.java, src/main/java/io/github/bbortt/event/planner/service/InvitationService.java
* includes https://github.com/bbortt/ngx-autocomplete/pull/2.
* improves logging on service level
* removes useless annotations on repository level
=> correct one or two little things I've noticed.

src/main/java/io/github/bbortt/event/planner/domain/Project.java, src/main/java/io/github/bbortt/event/planner/domain/User.java, src/main/java/io/github/bbortt/event/planner/service/ProjectService.java, src/main/java/io/github/bbortt/event/planner/service/UserService.java, src/main/java/io/github/bbortt/event/planner/web/rest/errors/ExceptionTranslator.java, src/main/webapp/app/view/project/admin/locations/project-locations.component.html, src/main/webapp/app/view/project/admin/project-admin-update.component.ts, src/main/webapp/i18n/de/global.json, src/main/webapp/i18n/en/global.json, src/test/java/io/github/bbortt/event/planner/service/UserServiceIT.java
=> bugfix domain models and fullbuild application.

src/main/webapp/app/entities/location/location.service.ts, src/main/webapp/app/entities/project/project.resolve.ts, src/main/webapp/app/entities/project/project.service.ts, src/main/webapp/app/shared/model/project.model.ts, src/main/webapp/app/view/my-projects/my-projects.component.ts, src/main/webapp/app/view/project/screenplay/project-screenplay-location.component.html, src/main/webapp/app/view/project/screenplay/project-screenplay-location.component.scss, src/main/webapp/app/view/project/screenplay/project-screenplay-location.component.ts
another screenplay improvement: custom from - to view.
=> #12 scheduler view with custom interval.

src/main/webapp/app/view/project/admin/locations/project-location-modal.component.ts, src/main/webapp/app/view/project/admin/locations/project-location-update.component.html, src/main/webapp/app/view/project/admin/locations/project-location-update.component.ts, src/main/webapp/app/view/project/admin/locations/sections/project-section-modal.component.ts, src/main/webapp/app/view/project/admin/locations/sections/project-section-update.component.html, src/main/webapp/app/view/project/admin/locations/sections/project-section-update.component.ts, src/main/webapp/app/view/project/admin/responsibilities/project-responsibility-modal.component.ts
=> minor bugs i noticed while working on the project.

src/main/webapp/app/entities/event/event.resolve.ts, src/main/webapp/app/entities/event/event.service.ts, src/main/webapp/app/entities/location/location.service.ts, src/main/webapp/app/entities/section/section.service.ts, src/main/webapp/app/shared/model/event.model.ts, src/main/webapp/app/shared/model/scheduler/event.scheduler.ts, src/main/webapp/app/view/project/screenplay/event/event-update-modal.component.ts, src/main/webapp/app/view/project/screenplay/project-screenplay-location.component.ts
PR contains:
* bugfix new `Event` dates url params
* correct frontend `Event` model implementation
\+ bugfixing `moment`s in `Project` via frontend services in d9dc33222dc66ecae1bac29c59b36d3446e9b6d9.
=> pass new event dates as JSON, so it is a legal url query param.

src/main/java/io/github/bbortt/event/planner/repository/SectionRepository.java, src/main/java/io/github/bbortt/event/planner/service/SectionService.java, src/main/java/io/github/bbortt/event/planner/web/rest/LocationResource.java, src/main/java/io/github/bbortt/event/planner/web/rest/ResponsibilityResource.java, src/main/java/io/github/bbortt/event/planner/web/rest/SectionResource.java, src/main/webapp/app/entities/section/section.service.ts, src/main/webapp/app/entities/validator/unique-property-value-in-location.validator.ts, src/main/webapp/app/view/project/admin/locations/sections/project-section-update.component.html, src/main/webapp/app/view/project/admin/locations/sections/project-section-update.component.ts, src/test/java/io/github/bbortt/event/planner/service/SectionServiceUnitTest.java, src/test/java/io/github/bbortt/event/planner/web/rest/SectionResourceIT.java, src/test/javascript/spec/app/entities/validator/unique-property-value-in-location.validator.spec.ts
=> section name uniqueness check

src/main/webapp/app/view/project/admin/locations/project-location-update.component.ts, src/main/webapp/app/view/project/admin/locations/sections/project-section-update.component.ts, src/main/webapp/app/view/project/admin/responsibilities/project-responsibility-update.component.ts
assign uniqueness validator once upon value change.
=> add uniqueness validator on value change once.

src/main/webapp/app/view/my-projects/my-projects.component.html
hide project buttons on md screens.
=> fix my-projects buttons on md screens.

src/main/webapp/app/view/project/admin/users/project-user-invite.component.html, src/main/webapp/app/view/project/admin/users/project-user-invite.component.ts, src/main/webapp/app/view/project/admin/users/project-users.component.html
`User` with `Role` `ADMIN` should be able to assign a `Responsibility` to himself.
=> project ADMIN can edit responsibility.

src/main/webapp/app/view/project/admin/users/project-user-invite.component.html
originates from #172. fixes #177.
=> User invite: Role value is optional

src/main/webapp/app/view/project/admin/users/project-user-invite.component.html, src/main/webapp/app/view/project/admin/users/project-user-invite.component.ts, src/main/webapp/i18n/de/global.json, src/main/webapp/i18n/en/global.json
=> remove role selection dropdown.

.github/workflows/gradle-dependency-report.yml, .github/workflows/gradle-fullbuild.yml, .github/workflows/gradle-preview.yml, DEVELOPMENT.md, LICENSE, README.md, backend/README.md, backend/src/main/resources/i18n/messages.properties, backend/src/main/resources/i18n/messages_de.properties, backend/src/main/resources/i18n/messages_en.properties, backend/src/main/resources/templates/mail/invitationEmail.html, backend/src/test/resources/config/application.yml, build.gradle, frontend/README.md, frontend/build.gradle, gateway/README.md, services/user/README.md, services/user/src/main/resources/config/application-prod.yml, services/user/src/test/resources/config/application.yml
=> #204 extended documentation for each individual component.

backend/src/main/java/io/github/bbortt/event/planner/backend/client/UserServiceFeignClient.java, backend/src/main/java/io/github/bbortt/event/planner/backend/client/UserServiceFeignClientFallback.java, backend/src/main/java/io/github/bbortt/event/planner/backend/config/FeignConfiguration.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/UserService.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/mapper/EventMapper.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/mapper/InvitationMapper.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/mapper/LocationMapper.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/mapper/SectionMapper.java, backend/src/test/java/io/github/bbortt/event/planner/backend/web/rest/InvitationResourceIT.java
=> #209 follow up on hystrix fallbacks.

backend/src/main/java/io/github/bbortt/event/planner/backend/domain/Project.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/EventService.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/ProjectService.java, backend/src/test/java/io/github/bbortt/event/planner/backend/service/EventServiceUnitTest.java, backend/src/test/java/io/github/bbortt/event/planner/backend/web/rest/EventResourceIT.java, backend/src/test/java/io/github/bbortt/event/planner/backend/web/rest/ProjectResourceIT.java, frontend/src/main/webapp/app/entities/event/event-update.component.html, frontend/src/main/webapp/app/view/project/calendar/project-calendar.component.ts, frontend/src/main/webapp/i18n/de/project.calendar.json, frontend/src/main/webapp/i18n/en/project.calendar.json
PR contains the following bugfixes:
* can no longer create events out of project bounds
* can no longer select calendar days out of project bounds
* can now select sections instead of locations in the event-update modal
=> #198 add event time bounds security.

backend/src/main/java/io/github/bbortt/event/planner/backend/config/SecurityConfiguration.java, backend/src/main/java/io/github/bbortt/event/planner/backend/service/ProjectService.java, backend/src/test/java/io/github/bbortt/event/planner/backend/service/EventServiceUnitTest.java, frontend/src/main/webapp/app/view/project/calendar/filter/project-calendar-filter.component.ts, frontend/src/main/webapp/app/view/project/calendar/project-calendar.component.html, frontend/src/main/webapp/app/view/project/calendar/project-calendar.component.ts
=> #229 persist calendar state in route query params.

.github/workflows/test.yml, build.gradle, gradle.properties, settings.gradle
so we can analyze coverage and code quality for future changes.
=> ci(sonar): enable sonarqube reports

src/main/java/io/github/bbortt/event/planner/config/GraphQLScalarsConfig.java, src/main/java/io/github/bbortt/event/planner/domain/Auth0User.java, src/main/java/io/github/bbortt/event/planner/domain/Locality.java, src/main/java/io/github/bbortt/event/planner/domain/Member.java, src/main/java/io/github/bbortt/event/planner/domain/MemberPermission.java, src/main/java/io/github/bbortt/event/planner/domain/MemberPermissionId.java, src/main/java/io/github/bbortt/event/planner/domain/Permission.java, src/main/java/io/github/bbortt/event/planner/domain/Project.java, src/main/java/io/github/bbortt/event/planner/graphql/dto/LocalityCreateInput.java, src/main/java/io/github/bbortt/event/planner/graphql/dto/LocalityUpdateInput.java, src/main/java/io/github/bbortt/event/planner/graphql/resolver/LocalityMutationResolver.java, src/main/java/io/github/bbortt/event/planner/graphql/resolver/ProjectQueryResolver.java, src/main/java/io/github/bbortt/event/planner/repository/LocalityRepository.java, src/main/java/io/github/bbortt/event/planner/repository/PermissionRepository.java, src/main/java/io/github/bbortt/event/planner/service/LocalityService.java, src/main/java/io/github/bbortt/event/planner/service/PermissionService.java, src/main/java/io/github/bbortt/event/planner/service/ProjectService.java, src/main/resources/schema/locality.graphqls, src/test/java/io/github/bbortt/event/planner/graphql/resolver/LocalityMutationResolverIntegrationTest.java, src/test/java/io/github/bbortt/event/planner/graphql/resolver/LocalityMutationResolverUnitTest.java, src/test/java/io/github/bbortt/event/planner/graphql/resolver/ProjectMutationResolverIntegrationTest.java, src/test/java/io/github/bbortt/event/planner/graphql/resolver/ProjectQueryResolverUnitTest.java, src/test/java/io/github/bbortt/event/planner/service/LocalityServiceUnitTest.java, src/test/java/io/github/bbortt/event/planner/service/PermissionServiceUnitTest.java, src/test/java/io/github/bbortt/event/planner/service/ProjectServiceUnitTest.java, src/test/resources/graphql/create-locality.graphql
* backend implementation to create localities
* permission checking system (on project level) for the backend
* includes testset
=> locality backend implementation

.github/labeler.yml, .github/workflows/pull-requests.yml, .github/workflows/sonar.yml, apps/projects-service/sonar-project.properties, apps/projects-service/src/test/java/io/github/bbortt/event/planner/apps/projects/ProjectsServiceApplicationIntegrationTest.java, sonar-project.properties
fixes the sonar warnings, property `multicriteria` is no longer picked up from modules.
=> sonar cleanup

.github/workflows/main.yml
package application for prod only.
=> ci cd improvements

DEVELOPMENT.md, src/main/java/io/github/bbortt/event/planner/service/ProjectService.java, src/main/java/io/github/bbortt/event/planner/service/dto/ProjectDTO.java, src/main/java/io/github/bbortt/event/planner/web/rest/ProjectResource.java, src/main/webapp/app/admin/entity-audit/entity-audit.component.html, src/main/webapp/app/admin/logs/logs.component.html, src/main/webapp/app/admin/metrics/blocks/jvm-memory/jvm-memory.component.html, src/main/webapp/app/admin/metrics/blocks/jvm-threads/jvm-threads.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-cache/metrics-cache.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-datasource/metrics-datasource.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-endpoints-requests/metrics-endpoints-requests.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-garbagecollector/metrics-garbagecollector.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-request/metrics-request.component.html, src/main/webapp/app/admin/metrics/blocks/metrics-system/metrics-system.component.html, src/main/webapp/app/admin/tracker/tracker.component.html, src/main/webapp/app/entities/common/auditing-entity.model.ts, src/main/webapp/app/entities/project/project.model.ts, src/main/webapp/app/entities/project/project.test-samples.ts, src/main/webapp/app/entities/project/update/project-form.service.ts, src/test/java/io/github/bbortt/event/planner/service/ProjectServiceUnitTest.java, src/test/java/io/github/bbortt/event/planner/web/rest/ProjectResourceIT.java, src/test/java/io/github/bbortt/event/planner/web/rest/PublicUserResourceIT.java
it is now possible to create (or rather post) a new project with default values. backend fails to persist it.
=> chore: create project modal

package-lock.json, package.json, src/main/webapp/app/entities/location/service/location.service.ts, src/main/webapp/app/entities/location/update/location-update.component.ts, src/main/webapp/app/entities/member/service/member.service.ts, src/main/webapp/app/entities/member/update/member-update.component.ts, src/main/webapp/app/entities/project/service/project.service.ts, src/main/webapp/app/entities/project/update/project-update.component.ts, src/main/webapp/app/home/home.component.html, src/main/webapp/app/home/projects/admin/layout/admin-layout.component.html, src/main/webapp/app/home/projects/admin/member/project-member-list.component.html, src/main/webapp/app/home/projects/admin/member/project-member-list.component.ts, src/main/webapp/app/home/projects/admin/project-admin.module.ts, src/main/webapp/app/home/projects/admin/project-admin.route.ts, src/main/webapp/app/home/projects/admin/route/project-from-parent-resolve.service.spec.ts, src/main/webapp/app/home/projects/admin/settings/project-settings.component.ts, src/main/webapp/app/home/projects/mine/my-projects-list.component.html, src/main/webapp/app/home/projects/mine/my-projects-list.component.ts, src/main/webapp/app/home/projects/mine/project-card.component.html, src/main/webapp/app/home/projects/projects.route.ts, src/main/webapp/app/layouts/main/main.component.html, src/main/webapp/app/layouts/profiles/profile.service.ts, tsconfig.json
=> project member list (copy of entity list)

.github/workflows/preview.yml, src/main/webapp/app/app-routing.module.ts, src/main/webapp/app/home/projects/admin/layout/admin-layout.component.html, src/main/webapp/app/home/projects/admin/member/project-member-list.component.html, src/main/webapp/app/home/projects/admin/settings/project-settings.component.html, src/main/webapp/app/home/projects/mine/my-projects-list.component.html, src/main/webapp/app/invitation/invitation.module.ts, src/main/webapp/app/invitation/invitation.route.ts, src/main/webapp/app/invitation/projects/project-invitation-login.component.html, src/main/webapp/app/invitation/projects/project-invitation-login.component.spec.ts, src/main/webapp/app/invitation/projects/project-invitation-login.component.ts, src/main/webapp/app/invitation/projects/project-invitation.component.html, src/main/webapp/app/invitation/projects/project-invitation.component.ts, src/main/webapp/app/invitation/projects/project-invitation.module.ts, src/main/webapp/app/invitation/projects/project-invitation.route.ts, src/main/webapp/i18n/de/project-invitation.json, src/main/webapp/i18n/en/project-invitation.json
prepare the project invitation frontend components.
=> project invitation component

.github/workflows/pull-requests.yml, build.gradle, gradle.properties, package-lock.json, package.json
also includes #787, but with fixed `snakeyaml` version.
=> dependency updates

src/main/webapp/app/entities/event/update/event-update.component.ts, src/main/webapp/app/entities/location/update/location-update.component.ts, src/main/webapp/app/entities/member/update/member-update.component.ts, src/main/webapp/app/home/projects/admin/events/project-event-list.component.html, src/main/webapp/app/home/projects/admin/events/project-event-list.component.ts, src/main/webapp/app/home/projects/admin/events/update/project-event-update.component.spec.ts, src/main/webapp/app/home/projects/admin/events/update/project-event-update.component.ts, src/main/webapp/app/home/projects/calendar/event-to-calendar-event.spec.ts, src/main/webapp/app/home/projects/calendar/event-to-calendar-event.ts, src/main/webapp/app/home/projects/calendar/project-calendar.component.html, src/main/webapp/app/home/projects/calendar/project-calendar.component.spec.ts, src/main/webapp/app/home/projects/calendar/project-calendar.component.ts, src/main/webapp/app/home/projects/calendar/project-calendar.module.ts
- recursive flatmapping of locations for event edit
- added time information on project events
- cleaned up some wrongly written pipes
- switch calendar times from `date-fns` to `dayjs`
- add event to calendar event mapping
=> various fixes around project events
